// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc0iazrB6qHHnFzznh9jojuNcRmGTlzk0',
    appId: '1:374384065816:web:f030c89ec3e0bb73a8326d',
    messagingSenderId: '374384065816',
    projectId: 'codemehub-project',
    authDomain: 'codemehub-project.firebaseapp.com',
    storageBucket: 'codemehub-project.appspot.com',
    measurementId: 'G-KMSTREGWYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy6ST2K6K1bwDzd0RuSF_3d4Z_6IP-EfY',
    appId: '1:374384065816:android:7dac757ed63b15dea8326d',
    messagingSenderId: '374384065816',
    projectId: 'codemehub-project',
    storageBucket: 'codemehub-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa1-t-kj0ekXvJkXnEUUNHsfyF-2UtVRc',
    appId: '1:374384065816:ios:613b457298164005a8326d',
    messagingSenderId: '374384065816',
    projectId: 'codemehub-project',
    storageBucket: 'codemehub-project.appspot.com',
    iosBundleId: 'com.example.codemehubProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa1-t-kj0ekXvJkXnEUUNHsfyF-2UtVRc',
    appId: '1:374384065816:ios:613b457298164005a8326d',
    messagingSenderId: '374384065816',
    projectId: 'codemehub-project',
    storageBucket: 'codemehub-project.appspot.com',
    iosBundleId: 'com.example.codemehubProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc0iazrB6qHHnFzznh9jojuNcRmGTlzk0',
    appId: '1:374384065816:web:986d068747359d75a8326d',
    messagingSenderId: '374384065816',
    projectId: 'codemehub-project',
    authDomain: 'codemehub-project.firebaseapp.com',
    storageBucket: 'codemehub-project.appspot.com',
    measurementId: 'G-JKBLBTFPBC',
  );
}
